services:
  server:
    image: patientor-backend
    build:
      context: ./patientor-backend/
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
   
    volumes:
      - ./patientor-backend:/usr/src/app
   
    container_name: patientor-backend
  
  app:
    environment:
      - REACT_APP_BACKEND_URL=/api/
    image: patientor-frontend
    build:
      context: ./patientor-frontend/ # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./patientor-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: patientor-frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-prod
    depends_on:
      - server
      - app # wait for the frontend container to be started